---
#First try of an ansible import_playbook
- name: Install HTTPD and MariaDB
  hosts: linux
  
  tasks:
  - name: Install HTTPD
    dnf:
      name: httpd
      state: latest
        
  - name: Install MariaDB
    dnf:
      name: mariadb-server
      state: latest