---
#First try of an ansible import_playbook
- name: Install HTTPD and MariaDB
  hosts: linux
  
  tasks:
  - name: Install services
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - mariadb-server
    when: ansible_distribution == 'Fedora'